spring.application.name=notificaciones
server.port=${PORT:6770}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ecommerce_frank}
spring.datasource.username=${DATABASE_USERNAME:frank}
spring.datasource.password=${DATABASE_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME:viasusriveradesarrollo@gmail.com}
spring.mail.password=${SMTP_PASSWORD:1070464242S@muel}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

management.endpoints.web.exposure.include=health,info
